### ISSUE TITLE
Partial info on note

### ISSUE THREAD

**Issue by kevchu3** [IronicBadger/openshift-compendium#25]
@IronicBadger

I noticed that the [quotas-and-limits-demo.md](https://github.com/IronicBadger/openshift-compendium/blob/dev/notes/quotas-and-limits-demo.md) note has been partially written.  Do you suggest to add the full text or clean up the note snippet and leave just the link?

**Comment by ironicbadger** [comment]
I wasn't sure how we should handle what is essentially just a link to somewhere else. I put the beginning of the readme into the compendium but not the whole article because it wouldn't stay in sync unless we did it so that when folks search, they get *something*.

Open to suggestions.

**Comment by kevchu3** [comment]
The markdown style heading makes it appear as a table of contents, so the 'Full text and examples at the link above.' doesn't capture as much attention.  I wonder if blockquotes (not sure if that'd work) or code or anything else to strip the formatting from the quoted article would be better.

**Comment by kevchu3** [comment]
Closing this stale issue
